# Generated by Django 3.2.15 on 2022-08-12 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.FloatField(db_index=True, verbose_name='Czas'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to='recording/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='frequency',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='Częstotliwość'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date',
            field=models.DateTimeField(db_index=True, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordings', models.ManyToManyField(to='sdr.Recording', verbose_name='Lista nagrań')),
            ],
            options={
                'verbose_name': 'Recording session',
                'verbose_name_plural': 'Recording sessions',
            },
        ),
    ]
