# Generated by Django 3.2.15 on 2022-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0002_auto_20220812_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_frequency', models.PositiveBigIntegerField(db_index=True, verbose_name='Początek (częstotliwość)')),
                ('end_frequency', models.PositiveBigIntegerField(db_index=True, verbose_name='Koniec (częstotliwość)')),
                ('step_frequency', models.PositiveIntegerField(db_index=True, verbose_name='Krok (częstotliwość)')),
                ('begin_model_date', models.DateTimeField(db_index=True, verbose_name='Początek modelu (data)')),
                ('end_model_date', models.DateTimeField(db_index=True, verbose_name='Koniec modelu (data)')),
                ('begin_real_date', models.DateTimeField(db_index=True, verbose_name='Początek danych (data)')),
                ('end_real_date', models.DateTimeField(db_index=True, verbose_name='Koniec danych (data)')),
                ('labels', models.BinaryField(verbose_name='Etykiety')),
                ('data', models.BinaryField(verbose_name='Dane')),
            ],
            options={
                'unique_together': {('begin_frequency', 'end_frequency', 'step_frequency', 'begin_model_date', 'end_model_date')},
            },
        ),
    ]
