# Generated by Django 3.2.15 on 2022-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0003_spectrogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_frequency', models.PositiveBigIntegerField(db_index=True, verbose_name='Początek (częstotliwość)')),
                ('end_frequency', models.PositiveBigIntegerField(db_index=True, verbose_name='Koniec (częstotliwość)')),
                ('step_frequency', models.PositiveIntegerField(db_index=True, verbose_name='Krok (częstotliwość)')),
                ('begin_date', models.DateTimeField(db_index=True, verbose_name='Początek (data)')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='Koniec (data)')),
                ('sample_size', models.PositiveIntegerField(db_index=True, verbose_name='Rozmiar próbki')),
                ('data', models.BinaryField(verbose_name='Dane')),
            ],
        ),
    ]
