# Generated by Django 3.2.15 on 2022-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0004_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrogram',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='data',
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='data_file',
            field=models.FileField(default='', upload_to='spectrogram/%Y-%m-%d/', verbose_name='Plik danych'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmission',
            name='data_file',
            field=models.FileField(default='', upload_to='transmission/%Y-%m-%d/', verbose_name='Plik danych'),
            preserve_default=False,
        ),
    ]
