# Generated by Django 3.2.15 on 2022-09-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0005_auto_20220830_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmission',
            name='step_frequency',
        ),
    ]
