# Generated by Django 3.2.15 on 2022-09-13 16:20

from django.db import migrations, models
import django.db.models.deletion
import sdr.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0006_remove_transmission_step_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('raw_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Nazwa robocza')),
            ],
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='device',
            field=models.ForeignKey(default=sdr.models.default_device, on_delete=django.db.models.deletion.CASCADE, to='sdr.device'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='device',
            field=models.ForeignKey(default=sdr.models.default_device, on_delete=django.db.models.deletion.CASCADE, to='sdr.device'),
        ),
        migrations.AlterUniqueTogether(
            name='spectrogram',
            unique_together={('device', 'begin_frequency', 'end_frequency', 'step_frequency', 'begin_model_date', 'end_model_date')},
        ),
    ]
