# Generated by Django 3.2.15 on 2023-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0009_auto_20230102_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='raw_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Raw name'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='begin_frequency',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='Begin (frequency)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='begin_model_date',
            field=models.DateTimeField(db_index=True, verbose_name='Begin (model)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='begin_real_date',
            field=models.DateTimeField(db_index=True, verbose_name='Begin (data)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='data_file',
            field=models.FileField(upload_to='spectrogram/%Y-%m-%d/', verbose_name='Data file'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='end_frequency',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='End (frequency)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='end_model_date',
            field=models.DateTimeField(db_index=True, verbose_name='End (model)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='end_real_date',
            field=models.DateTimeField(db_index=True, verbose_name='End (data)'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='labels',
            field=models.BinaryField(verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='step_frequency',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Step (frequency)'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='begin_date',
            field=models.DateTimeField(db_index=True, verbose_name='Begin (date)'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='begin_frequency',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='Begin (frequency)'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='data_file',
            field=models.FileField(upload_to='transmission/%Y-%m-%d/', verbose_name='Data file'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='data_type',
            field=models.CharField(max_length=255, verbose_name='Data type'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='end_date',
            field=models.DateTimeField(db_index=True, verbose_name='End (date)'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='end_frequency',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='End (frequency)'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='sample_size',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Sample size'),
        ),
    ]
