# Generated by Django 3.2.15 on 2023-02-14 20:17

from django.db import migrations, models
import django.db.models.deletion
import sdr.models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0010_auto_20230206_0847"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("data_type", models.CharField(max_length=255, verbose_name="Data type")),
            ],
        ),
        migrations.AddField(
            model_name="transmission",
            name="modulation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sdr.modulation"),
        ),
    ]
