# Generated by Django 3.2.15 on 2023-02-16 15:25

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion
import sdr.models


def update_groups(apps, schema_editor):
    default_group_id = sdr.models.Group.objects.get_or_create(name="Default", begin_frequency=0, end_frequency=10000000000, modulation="FM")[0].id
    sdr.models.Transmission.objects.update(group_id=default_group_id)

    sdr.models.Group.objects.get_or_create(name="Airband", begin_frequency=108000000, end_frequency=137000000, modulation="AM")
    sdr.models.Group.objects.get_or_create(name="Amateur radio 10 m", begin_frequency=28000000, end_frequency=29700000, modulation="FM")
    sdr.models.Group.objects.get_or_create(name="Amateur radio 2 m", begin_frequency=144000000, end_frequency=146000000, modulation="FM")
    sdr.models.Group.objects.get_or_create(name="Amateur radio 70 cm", begin_frequency=430000000, end_frequency=440000000, modulation="FM")
    sdr.models.Group.objects.get_or_create(name="PMR 446", begin_frequency=446000000, end_frequency=446200000, modulation="FM")

    for group in sdr.models.Group.objects.annotate(bandwidth=F("end_frequency") - F("begin_frequency")).order_by("-bandwidth").all():
        sdr.models.Transmission.objects.annotate(frequency=(F("begin_frequency") + F("end_frequency")) / 2).filter(
            frequency__gte=group.begin_frequency, frequency__lte=group.end_frequency
        ).update(group_id=group.id)


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0011_auto_20230214_2117"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
                ("modulation", models.CharField(max_length=255, verbose_name="Modulation")),
                ("begin_frequency", models.PositiveBigIntegerField(db_index=True, verbose_name="Begin frequency")),
                ("end_frequency", models.PositiveBigIntegerField(db_index=True, verbose_name="End frequency")),
                ("data_type", models.CharField(max_length=255, verbose_name="Data type", default="audio")),
            ],
        ),
        migrations.RemoveField(
            model_name="transmission",
            name="modulation",
        ),
        migrations.DeleteModel(
            name="Modulation",
        ),
        migrations.AddField(
            model_name="transmission",
            name="group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sdr.group"),
        ),
        migrations.RunPython(update_groups),
        migrations.AlterField(
            model_name="transmission",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sdr.group"),
        ),
    ]
