# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa")),
                ("serial", models.CharField(max_length=255, verbose_name="Numer seryjny")),
                ("enabled", models.BooleanField(default=True, verbose_name="Aktywny")),
                ("visible", models.BooleanField(default=True, verbose_name="Widoczny")),
                ("domoticzId", models.IntegerField(default=0, verbose_name="Domoticz ID")),
                ("posted_date", models.DateTimeField(auto_now_add=True, verbose_name="Data dodania")),
            ],
            options={"verbose_name": "Czujnik", "verbose_name_plural": "Czujniki",},
        ),
        migrations.CreateModel(
            name="TemperatureMeasurement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Temperatura")),
                ("posted_date", models.DateTimeField(auto_now_add=True, verbose_name="Data dodania")),
                ("sensor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="graphs.Sensor", verbose_name="Czujnik")),
            ],
            options={"verbose_name": "Pomiar temperatury", "verbose_name_plural": "Pomiary temperatury",},
        ),
    ]
