# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0002_sensorsgroup"),
    ]

    operations = [migrations.RenameModel("TemperatureMeasurement", "Measurement"), migrations.RenameField("Measurement", "temperature", "value")]
