# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0003_auto_20190427_0844"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa")),
                ("raw_name", models.CharField(max_length=255, verbose_name="Surowa nazwa")),
                ("digits", models.IntegerField(default=0, verbose_name="Dokładność")),
                ("unit", models.CharField(max_length=255, verbose_name="Jednostka")),
                ("posted_date", models.DateTimeField(auto_now_add=True, verbose_name="Data dodania")),
            ],
            options={"verbose_name": "Typ czujnika", "verbose_name_plural": "Typy czujników",},
        ),
        migrations.AlterModelOptions(name="measurement", options={"verbose_name": "Pomiar", "verbose_name_plural": "Pomiary"},),
        migrations.AlterField(model_name="measurement", name="value", field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Wartość"),),
        migrations.AddField(
            model_name="sensor",
            name="sensor_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="graphs.SensorType", verbose_name="Typ czujnika"),
            preserve_default=False,
        ),
    ]
