# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0004_auto_20190427_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_type",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="graphs.SensorType", verbose_name="Typ czujnika"),
            preserve_default=False,
        ),
    ]
