# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0005_auto_20190427_1118"),
    ]

    operations = [
        migrations.AlterField(model_name="sensortype", name="unit", field=models.CharField(max_length=255, null=True, verbose_name="Jednostka"),),
    ]
