# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0006_auto_20190427_1136"),
    ]

    operations = [
        migrations.AlterField(model_name="sensortype", name="digits", field=models.IntegerField(default=2, verbose_name="Dokładność"),),
    ]
