# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0008_auto_20190427_1141"),
    ]

    operations = [
        migrations.AddField(model_name="sensortype", name="visible", field=models.BooleanField(default=True, verbose_name="Widoczny"),),
    ]
