# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0010_auto_20190427_1429"),
    ]

    operations = [
        migrations.AlterField(model_name="measurement", name="value", field=models.FloatField(verbose_name="Wartość"),),
    ]
