# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graphs", "0011_auto_20190427_1440"),
    ]

    operations = [
        migrations.RemoveField(model_name="sensorsgroup", name="enabled",),
        migrations.AddField(model_name="sensorsgroup", name="visible", field=models.BooleanField(default=True, verbose_name="Widoczna"),),
    ]
