# Generated by Django 3.1.2 on 2020-10-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0012_auto_20190428_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sensorsgroup',
            options={'verbose_name': 'Sensor group', 'verbose_name_plural': 'Sensor groups'},
        ),
        migrations.AlterModelOptions(
            name='sensortype',
            options={'verbose_name': 'Sensor type', 'verbose_name_plural': 'Sensor types'},
        ),
    ]
