# Generated by Django 3.1.3 on 2022-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0013_auto_20201002_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='serial',
            field=models.CharField(max_length=255, unique=True, verbose_name='Numer seryjny'),
        ),
    ]
