# Generated by Django 3.1.3 on 2022-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0015_sensor_last_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='raw_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Surowa nazwa'),
        ),
    ]
