# Generated by Django 3.2.15 on 2023-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0016_auto_20220807_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data dodania'),
        ),
    ]
