# Generated by Django 3.2.15 on 2023-10-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0017_alter_measurement_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='domoticzId',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='enabled',
        ),
    ]
