# Generated by Django 4.2.6 on 2024-02-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("graphs", "0018_auto_20231024_0024"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Początek zakresu"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Koniec zakresu"
                    ),
                ),
                (
                    "last_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ostatni zakres (ilość próbek)",
                    ),
                ),
                (
                    "last_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="",
                        max_length=255,
                        verbose_name="Ostatni zakres (typ próbek)",
                    ),
                ),
                (
                    "aggregation_time",
                    models.CharField(
                        choices=[
                            ("minute", "Minute"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="minute",
                        max_length=255,
                        verbose_name="Czas agregacji",
                    ),
                ),
                ("min_max", models.BooleanField(default=False, verbose_name="Min max")),
            ],
        ),
        migrations.AddField(
            model_name="sensorsgroup",
            name="preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="graphs.preset",
                verbose_name="Typ czujnika",
            ),
        ),
    ]
