# Generated by Django 3.1.2 on 2020-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201002_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='posted_date',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
    ]
