# Generated by Django 3.1.2 on 2020-10-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_auto_20201002_1503"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referrer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024, unique=True, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="referrer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="logs.referrer")
        ),
    ]
