# Generated by Django 3.2.15 on 2023-10-25 06:55

from django.db import migrations, models
import django.db.models.deletion
import logs.models


def update(apps, schema_editor):
    default_domain_id = logs.models.Domain.objects.get_or_create(name="")[0].id
    default_method_id = logs.models.Method.objects.get_or_create(name="")[0].id
    default_protocol_id = logs.models.Protocol.objects.get_or_create(name="")[0].id
    logs.models.Request.objects.update(domain_id=default_domain_id, method_id=default_method_id, protocol_id=default_protocol_id)


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_auto_20201004_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024, unique=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024, unique=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024, unique=True, verbose_name="Name")),
            ],
        ),
        migrations.RemoveField(
            model_name="request",
            name="raw",
        ),
        migrations.AddField(
            model_name="request",
            name="domain",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="logs.domain"),
        ),
        migrations.AddField(
            model_name="request",
            name="method",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="logs.method"),
        ),
        migrations.AddField(
            model_name="request",
            name="protocol",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="logs.protocol"),
        ),
        migrations.RunPython(update),
        migrations.AlterField(
            model_name="request",
            name="domain",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="logs.domain"),
        ),
        migrations.AlterField(
            model_name="request",
            name="method",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="logs.method"),
        ),
        migrations.AlterField(
            model_name="request",
            name="protocol",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="logs.protocol"),
        ),
    ]
